#!/usr/bin/env sh

### /// hsm // ConzZah // 2026-05-02 01:16 ///

### /// hsm is a minimal nmcli-based hotspot manager /// ###

logo () {
printf '%s\n' '
                        888
                        888
                        888
                        88888b.  .d8888b  88888b.d88b.
                        888 "88b 88K      888 "888 "88b
                        888  888 "Y8888b. 888  888  888
                        888  888      X88 888  888  888
                        888  888  88888P  888  888  888' ;}

help () {
printf '\n%s\n' "         /// hsm v1.1 // Author: ConzZah (c) 2026 // LICENSE: MIT ///

 USAGE: hsm [OPTION]

 OPTIONS:

 h,      --help                              show this help and exit
 s,      --status                            show hotspot status
 e,      --enable                            enable hotspot
 d,      --disable                           disable hotspot
 th,     --toggle-hidden                     change hotspot visibility
 pw,     --view-pw                           view hotspot password
 chpw,   --change-pw                         change hotspot password
 chssid, --change-ssid                       change hotspot ssid
 --restore-default [wifi/eth]                restores default values 
";}

[ -z "$1" ] && logo && help && exit
case $1 in
H|h|'-H'|'-h'|'--HELP'|'--help') logo; help; exit;;
esac


init () {
## refuse to launch entirely if nmcli wasn't found
! command -v nmcli >/dev/null && { echo "PLEASE INSTALL NETWORKMANAGER FIRST." && exit 1 ;}

## check all other deps
deps="grep sed cut iw"
for dep in $deps; do
! command -v "$dep" >/dev/null && \
printf '\n%s\n' "--> ERROR: MISSING DEPENDENCY: $dep" && exit 1
done

### doso ###
## if user doesn't happen to be root,
## check if sudo / doas are available and set it, else echo error & exit 1
## should user be root, leave "$doso" empty
doso=""; [ "$(whoami)" != "root" ] && { 
command -v sudo >/dev/null && doso="sudo"
[ -z "$doso" ] && command -v doas >/dev/null && doso="doas"
[ -z "$doso" ] && { printf '\n%s\n' "--> ERROR: SUDO / DOAS NOT FOUND."; exit 1 ;}
}

## create & cd to working directory
wd="$HOME/.hsm"
uuidfile="$wd/uuids"
mkdir -p "$wd" && cd "$wd" || exit 1

## if ufw isn't installed OR not active, 
## set $noufw (disables ufw functions)
! command -v ufw >/dev/null || [ ! -f "/usr/sbin/ufw" ] && noufw="1"
$doso ufw status| grep -q 'inactive' && noufw="1"

## symlink iptables to /sbin/iptables if they aren't already.
[ -f "/usr/sbin/iptables" ] && [ ! -L "/sbin/iptables" ] && \
$doso ln -s "/usr/sbin/iptables" "/sbin/iptables"

## if mode was explicitly specified, (re)assign "$mode"
[ "$1" = "wifi" ] || [ "$1" = "eth" ] && mode="$1" && shift
[ "$2" = "wifi" ] || [ "$2" = "eth" ] && mode="$2"

init_vars # <-- init vars (while respecting $mode)

## if '--restore-default' was requested, or no uuidfile could be found, run initial_setup.
[ ! -f "$uuidfile" ] && printf '\n%s\n' "--> ERROR: UUIDFILE DOESN'T EXIST YET, STARTING SETUP.."
[ "$1" = "--restore-default" ] || [ ! -f "$uuidfile" ] && {
restore_default="1"; initial_setup "$mode"
}

## load profile and get current status
hs_status

### ARGUMENTS ###
## NOTE: $xp = only gets set if explicitly called by the user
## NOTE: $w = waitflag, set vars, but don't modify until $w is zero
case "$1" in
S|s|"--STATUS"|"--status")
xp="1"; hs_status; exit "$?";;

E|e|"--ENABLE"|"--enable")
hs_enable; exit "$?";;

D|d|"--DISABLE"|"--disable")
hs_disable; exit "$?";;

TH|th|"--TOGGLE-HIDDEN"|"--toggle-hidden")
toggle_hidden; exit "$?";;

PW|pw|"--VIEW-PW"|"--view-pw")
vhspw; exit "$?";;

CHPW|chpw|"--CHANGE-PW"|"--change-pw")
xp="1"; chspw; exit "$?";;

CHSSID|chssid|"--CHANGE-SSID"|"--change-ssid")
xp="1"; chssid; exit "$?";;

*) logo; help; exit;;
esac
}


hs_status () {
### load profile/uuid and get the current hotspot status 
## load uuid, if $uuidfile exist
[ -f "$uuidfile" ] && load_uuid

## only show info when the the function is called by the user then return 0, else continue
[ -n "$xp" ] && {
[ "$hss" = "e" ] && hss_hr="ENABLED" 
[ "$hss" = "d" ] && hss_hr="DISABLED"
printf '\n%s\n%s\n%s\n%s\n\n' "CON-NAME: $hsn" "STATE:    ${hss_hr}" "MODE:     $mode" "HIDDEN:   ${hs_hidden}"; return ;}

## check if an nmcli profile for $hs_uuid exists, should it not be there anymore, delete it and run initial_setup.
[ -n "$hs_uuid" ] && $doso nmcli -t c| { ! grep -q "$hs_uuid" ;} && { delete_uuid_if_exist
printf '\n%s\n' "--> ERROR: NMCLI PROFILE FOR $mode WASN'T FOUND, STARTING SETUP.."
restore_default="1"; initial_setup "$mode"
}

[ -n "$hs_uuid" ] && {
hsn="$($doso nmcli -t -f connection.id c s "$hs_uuid"| cut -d ':' -f 2)"
[ "$mode" = "wifi" ] && hs_hidden="$($doso nmcli -t -f 802-11-wireless.hidden c s "$hs_uuid"| cut -d ':' -f 2)"

## $hss returns either e for enabled, or d for disabled
$doso nmcli -t c s --active| grep -q "$hs_uuid" && hss="e" || hss="d" ;}

## if $hss is enabled, find out what interface we're using
[ "$hss" = "e" ] && ap_iface="$($doso nmcli -t c s "$hs_uuid"| grep interface| cut -d : -f 2)"
}


hs_enable () { x="e"
### enable hotspot
## probe interfaces, depending on which $mode is in use
"probe_${mode}_interfaces"
## check if hotspot is already enabled and return 0 if it is.
[ "$hss" = "e" ] && printf "\n--> HOTSPOT ALREADY ENABLED \n\n" && return 0
inetcheck; ufw_trigger ## <-- run inetcheck, ufw_trigger and enable the hotspot
! $doso nmcli c u "$hs_uuid" && printf "\n--> ERROR: HOTSPOT COULDN'T BE ENABLED \n\n" && return 1 \
|| printf "\n--> HOTSPOT ENABLED\n\n" && return 0
}


hs_disable () { x="d"
### disable hotspot
## check if hotspot is already disabled
[ "$hss" = "d" ] && printf "\n--> HOTSPOT ALREADY DISABLED \n\n" && return 0
! $doso nmcli c d "$hs_uuid" && { printf "\n--> ERROR: HOTSPOT COULDN'T BE DISABLED \n\n"; return 1 ;} \
|| ufw_trigger && printf "\n--> HOTSPOT DISABLED\n\n" && return 0 
}


toggle_hidden () {
### toggle network discoverability
[ "$mode" = "eth" ] && printf '\n%s\n' "CAN'T CHANGE VISIBILITY FOR ${mode}." && return 0
[ "$hs_hidden" = "yes" ] && $doso nmcli c m "$hs_uuid" 802-11-wireless.hidden "no" && hs_hidden="DISCOVERABLE"
[ "$hs_hidden" = "no" ] && $doso nmcli c m "$hs_uuid" 802-11-wireless.hidden "yes" && hs_hidden="HIDDEN"
printf '\n%s\n%s\n' "--> HOTSPOT SSID IS NOW $hs_hidden." "--> DON'T FORGET TO EDIT / RE-ADD YOUR NETWORK ON THE DEICES U WANT TO USE." 
}


vhspw () {
### view hotspot password
[ "$mode" = "eth" ] && printf '\n%s\n' "${mode} DOESN'T NEED A PASSWORD." && return 0
hspw="$($doso nmcli -t -s -f 802-11-wireless-security.psk c s "$hs_uuid"| cut -d ':' -f 2)"
printf '\n%s\n%s\n%s\n\n' "SSID: $hsn " "PASS: $hspw " "HIDDEN NETWORK: $hs_hidden "
## if qrencode is installed, show qr code:
command -v qrencode >/dev/null && {
[ "$hs_hidden" = "yes" ] && hs_hidden="true" || hs_hidden="" # <-- change "$hs_hidden" to true if yes or empty if no (so the qr code works)
printf '%s' "WIFI:S:$hsn;T:WPA;P:$hspw;H:$hs_hidden;;"| qrencode -t UTF8; echo "" ;}
exit
}


chspw () {
### change hotspot password
[ "$mode" = "eth" ] && printf '\n%s\n' "${mode} DOESN'T NEED A PASSWORD." && return 0
[ -n "$w" ] || [ -n "$xp" ] && {
printf "\nENTER NEW HOTSPOT PASSWORD\n\n"
hspw=""; read -r hspw

## check for errors
[ "${#hspw}" -lt "8" ] && { printf "\n--> ERROR: PASSWORD NEEDS AT LEAST 8 CHARS.\n"; chspw ;}
[ -z "$w" ] || [ -n "$xp" ] && { $doso nmcli c m "$hsn" wifi-sec.psk "$hspw"; printf "\nPASSWORD CHANGED!\n" ;}
}
}


chssid () {
### change hotspot ssid & profile name
[ -n "$w" ] || [ -n "$xp" ] && {
printf "\nENTER NEW HOTSPOT SSID:\n\n"
ssid=""; read -r ssid

## if $ssid is empty, restart
[ -z "$ssid" ] && printf '\n%s\n' "--> ERROR: SSID CAN'T BE EMPTY." && chssid

## only change $hsn to $ssid if $restore_default is set
[ -n "$restore_default" ] && hsn="$ssid"
}
[ -z "$w" ] || [ -n "$xp" ] && {
$doso nmcli c m "$hsn" ssid "$ssid"
$doso nmcli c m "$hsn" c.id "$ssid"
}
}


init_vars () {
### init vars while respecting $mode
mode="${mode:-wifi}" # <-- default operation mode (wifi if unset)
hsn="${mode}-ap" # <-- default name depending on mode [accepted value: any]
hs_hidden="no" # <-- default hotspot visibility [accepted value: yes/no]
hs_autoconnect="no" # <-- default autoconnect state [accepted value: yes/no]
wifi_ifname="wlan0" # <-- default interface for wifi hotspot
eth_ifname="eth0" # <-- default interface for ethernet bridge
hss=""; xp=""; w="" # <-- $hss, $xp and $w have to (initially) be empty
}


add_ufw_rules () {
### if ufw is installed, add rules to allow hotspot traffic
## (will only be called in initial_setup).
[ -n "$noufw" ] && return 0 # <-- should ufw not be installed, return.
printf '\n%s\n\n' "--> SETTING UP UFW RULES"
$doso ufw allow bootps # <-- DHCP
$doso ufw allow 53/udp # <-- DNS
$doso ufw allow 53/tcp
}


ufw_trigger () {
[ "$x" != "d" ] && add_ufw_rules
### changes ufw's default forward policy to accept or drop
### (depending on if we're enabling or disabling the ap)
[ -n "$noufw" ] && return 0
cfg="/etc/default/ufw"
dfp="DEFAULT_FORWARD_POLICY="
a="$dfp\"ACCEPT\""; d="$dfp\"DROP\""
[ "$x" = "e" ] && $doso sed -i "s/$d/$a/g" "$cfg"
[ "$x" = "d" ] && $doso sed -i "s/$a/$d/g" "$cfg"
printf '\n%s\n' "--> RELOADING UFW.."
$doso ufw reload; $doso ufw enable >/dev/null
}


probe_wifi_interfaces () {
ap_iface=""; wifi_ifaces=""
### find out if at least one wifi interface on this system is capable of ap mode and assign it's ifname.
## returns all avilable wifi interfaces, except p2p, seperated by spaces.
wifi_ifaces="$(nmcli -t dev| grep wifi| sed 's/p2p-dev-.*//g'| cut -d ':' -f 1| tr '\n' ' '| tr -s ' ')"
[ -z "$wifi_ifaces" ] && { printf "\n--> ERROR: FAILED TO FIND ANY WIFI INTERFACE.\n"; exit 1 ;}
[ -n "$wifi_ifaces" ] && {
for iface in $wifi_ifaces; do
ap_capable="$(nmcli -f WIFI-PROPERTIES.AP device show "$iface"| tr -s ' '| cut -d ' ' -f 2)" # <--  returns either yes or no.
## should $ap_capable return yes, set the $ap_iface and break out of the loop, else continue until none remain.
[ "$ap_capable" = "yes" ] && { ap_iface="$iface"; wifi_ifname="$iface"; break ;}
[ "$ap_capable" = "no" ] && :
done
}
## if "$ap_iface" is empty after the loop, it means that no suitable interface was found. if that happens, exit here.
[ -z "$ap_iface" ] && printf "\n--> ERROR: FAILED TO FIND ANY WIFI INTERFACE CAPABLE OF AP-MODE.\n\n" && exit 1 
## if uuid is set, get the saved interface name from the ap connection profile and check if it's the same as the detected one:
## should it not be the same, modify it to use the $ap_iface, so one can connect to it: 
[ -n "$hs_uuid" ] && {
saved_wifi_interface="$($doso nmcli -t c s "$hs_uuid"| grep "interface"| cut -d ':' -f 2)"
[ "$ap_iface" != "$saved_wifi_interface" ] && $doso nmcli c m "$hs_uuid" ifname "$ap_iface" 
check_pmf_support
}
}


probe_eth_interfaces () {
ap_iface=""; eth_ifaces=""
### find any ethernet interfaces and check what state they are in
## ( if state is -lt 100 we lock in )
eth_ifaces="$(nmcli -t dev| grep ethernet| cut -d : -f 1| tr '\n' ' ')"
[ -z "$eth_ifaces" ] && { printf "\n--> ERROR: FAILED TO FIND ANY ETHERNET INTERFACE.\n"; exit 1 ;}
[ -n "$eth_ifaces" ] && {
for iface in $eth_ifaces; do 
iface_state="$(nmcli -t device show "$iface"| grep STATE| cut -d : -f 2| cut -b 1-3| sed 's# ##g')"
[ "$iface_state" -lt "100" ] && eth_ifname="$iface" && ap_iface="$iface" && break
done
}
## if if $eth_ifaces were found but $ap_iface is still empty,
## then they are most likely in use.
[ -n "$eth_ifaces" ] && [ -z "$ap_iface" ] && \
printf '\n%s\n\n' "--> ERROR: ALL ETHERNET INTERFACES ARE IN USE." && return 1

## if a uuid has been loaded, modify the interface, shouldn't it be the same:
[ -n "$hs_uuid" ] && {
saved_eth_iface="$($doso nmcli -t c s "$hs_uuid"| grep interface| cut -d : -f 2)"
[ "$iface" != "$saved_eth_iface" ] && $doso nmcli c m "$hs_uuid" ifname "$eth_ifname" ;}
}


check_pmf_support () {
### check if the chosen wifi interface supports pmf (protected-management-frames)
## Goal: detect and disable pmf on legacy hardware, if required (should it not be available)
## Issue: NetworkManager tries to enable pmf on some 802.11g adapters,which fails,
## because 802.11g came out in 2003, pmf however was introduced with 802.11w in 2009.
## see for yourself, if interested:
## https://en.wikipedia.org/wiki/IEEE_802.11g-2003
## https://en.wikipedia.org/wiki/IEEE_802.11w-2009
####################################################
## get phy number of interface
pnum="$($doso iw dev "$ap_iface" info| grep 'wiphy'| cut -d ' ' -f 2)"
## find out if our interface is pmf capable.
## we do this by checking for AES-CMAC support.
$doso iw phy "phy${pnum}" info | grep -oq 'CMAC' && pmf_support="yes" || pmf_support="no"
[ "$pmf_support" = "yes" ] && $doso nmcli c m "$hs_uuid" 802-11-wireless-security.pmf 0 && return || \
[ "$pmf_support" = "no" ] && $doso nmcli c m "$hs_uuid" 802-11-wireless-security.pmf 1 && return
}


inetcheck () {
### checks if any interface is connected to the internet
printf "\nCHECKING INTERNET CONNECTION..\n\n"
all_active_interfaces="$($doso nmcli -t c s --active| sed 's/lo.*//g'| cut -d ':' -f 4| tr '\n' ' '| tr -s ' ')"
### ^ ^ ^ returns active interfaces (except loopback) seperated by spaces
## loops through every available interface, and breaks out once the ping to quad9 is successful
# I = interface to use, W = time to wait for response, c = count of pings to send, s = size of packets per ping in bytes 
inet_iface=""; interface=""
for interface in $all_active_interfaces; do
ping -I "$interface" -W 1 -c 1 -s 1 "quad9.net" >/dev/null && \
inet_iface="$interface" && break
done

## report whether or not we have an active internet connection
[ -z "$inet_iface" ] && printf "\n--> WARNING: NO INTERNET CONNECTION AVAILABLE. \n\nHOTSPOT WILL ONLY RUN LOCALLY.\n"
[ -n "$inet_iface" ] && printf '%s\n' "INET IFACE: $inet_iface"
## if ap and inet interface are NOT the same, there's nothing more to do, so we return 0.
[ "$inet_iface" != "$ap_iface" ] && \
printf '%s\n\n' "AP   IFACE: $ap_iface" && return 0
## however, if inet and ap interface ARE the same, echo error and exit
[ "$inet_iface" = "$ap_iface" ] && { printf '\n%s\n' "--> ERROR: '$ap_iface' CAN'T PROVIDE AP AND ACCESS THE INTERNET SIMULTANEOUSLY."; exit 1 ;}
}


install_nmcli_profiles () {
### install / restore nmcli connection profiles
## install default wifi ap profile only if we have a working interface
install_wifi_ap () {
delete_uuid_if_exist
probe_wifi_interfaces
## ask user for ssid & password
w="1"; chssid; chspw
## set up connection
$doso nmcli c a type wifi ifname "$wifi_ifname" con-name "$hsn" autoconnect "$hs_autoconnect" ssid "$hsn"
$doso nmcli c m "$hsn" 802-11-wireless.mode ap 802-11-wireless.band bg ipv4.method shared
$doso nmcli c m "$hsn" wifi-sec.key-mgmt wpa-psk wifi-sec.pairwise ccmp wifi-sec.proto rsn
$doso nmcli c m "$hsn" wifi-sec.psk "$hspw" 802-11-wireless.hidden "$hs_hidden"
w=""; chssid; chspw
}

## install default eth ap profile
install_eth_ap () {
delete_uuid_if_exist
probe_eth_interfaces
[ -n "$ap_iface" ] && \
$doso nmcli c add con-name "$hsn" type ethernet ifname "$eth_ifname" ipv4.method shared ipv6.method ignore autoconnect "$hs_autoconnect"
}

## if $1 is empty add ufw rules and default profiles.
[ -z "$1" ] && { add_ufw_rules; "install_${mode}_ap"; return ;}
[ "$1" = "wifi" ] && { add_ufw_rules; install_wifi_ap; return ;}
[ "$1" = "eth" ] && { add_ufw_rules; install_eth_ap; return ;}
}


initial_setup () {
### initial setup / uuid save function
hs_uuid=""; touch "$uuidfile"
install_nmcli_profiles "$1"
connections="$($doso nmcli -t c| sed -e 's#802-11-wireless#wifi#g' -e 's#802-3-ethernet#eth#g')"
## save uuid to uuidfile
hs_uuid="$(printf '%s' "$connections"| grep -m1 "$hsn")"
[ -n "$hs_uuid" ] && {
mode="$(printf '%s' "$hs_uuid"| cut -d ':' -f 3)"
hs_uuid="$(printf '%s' "$hs_uuid"|cut -d ':' -f 2)"
! grep -q "$hs_uuid" "$uuidfile" && \
printf '%s\n' "$mode:$hs_uuid" >> "$uuidfile"
}
printf '\n%s\n\n' "--> INITIAL SETUP DONE"
exit
}


delete_uuid_if_exist () {
## checks if a uuid and / or profile exists & deletes it from both locations
load_uuid; [ -n "$hs_uuid" ] && {
nmcli c | grep "$hs_uuid" >/dev/null && \
$doso nmcli c del "$hs_uuid"; hs_uuid="" ;}
## delete uuid for $mode if it was found in $uuidfile ($l stands for line)
l=""; l="$(grep -m1 -n "$mode" "$uuidfile"| cut -c 1)"
[ -n "$l" ] && sed -i "${l}d" "$uuidfile"
}


load_uuid () {
### try to load uuid
## or run initial setup for $mode, if it couldn't be loaded
## uuidfiles are built like this: "mode:uuid"
hs_uuid=""; hs_uuid="$(grep -m1 -s "$mode" "$uuidfile"| cut -d ':' -f 2)"
[ -z "$hs_uuid" ] && [ -z "$restore_default" ] && {
printf '\n%s\n' "--> NO UUID FOUND FOR: ${mode}, STARTING SETUP.."
restore_default="1"; initial_setup "$mode" ;}
[ -n "$hs_uuid" ] && return 0
}


init "$@"
